#!/usr/bin/env -S just --justfile

default:
  @just --list

install:
    pnpm install

update:
    pnpm update

#
build:
    CHATBOT_TARGET=web pnpm build

build-sidebar:
    CHATBOT_TARGET=vscode-sidebar pnpm build

build-toolbar:
    CHATBOT_TARGET=chrome-toolbar pnpm build

build-sidepanel:
    CHATBOT_TARGET=chrome-sidepanel pnpm build

# Build electron tray app
build-tray:
    CHATBOT_TARGET=electron-tray pnpm build

tidy:
    pnpm format
    pnpm lint
