#!/usr/bin/env -S just --justfile

default:
  @just --list

install:
    pnpm install

update:
    pnpm update

build:
    PAGES_BASE_PATH=/assistant CHATBOT_TARGET=web NEXT_PUBLIC_SENDER_ID=web pnpm build

# Build vscode sidebar
build-sidebar:
    PAGES_BASE_PATH="/{BASE_URL}" CHATBOT_TARGET=vscode-sidebar pnpm build

build-toolbar:
    PAGES_BASE_PATH= CHATBOT_TARGET=chrome-toolbar pnpm build

build-sidepanel:
    PAGES_BASE_PATH= CHATBOT_TARGET=chrome-sidepanel pnpm build

# Build electron tray app
build-tray:
    PAGES_BASE_PATH="/{BASE_URL}" CHATBOT_TARGET=electron-tray pnpm build

tidy:
    pnpm format
    pnpm lint